require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Core::CreationTagsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Core::CreationTag. As you add validations to Core::CreationTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Core::CreationTagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all core_creation_tags as @core_creation_tags" do
      creation_tag = Core::CreationTag.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:core_creation_tags)).to eq([creation_tag])
    end
  end

  describe "GET #show" do
    it "assigns the requested core_creation_tag as @core_creation_tag" do
      creation_tag = Core::CreationTag.create! valid_attributes
      get :show, {:id => creation_tag.to_param}, valid_session
      expect(assigns(:core_creation_tag)).to eq(creation_tag)
    end
  end

  describe "GET #new" do
    it "assigns a new core_creation_tag as @core_creation_tag" do
      get :new, {}, valid_session
      expect(assigns(:core_creation_tag)).to be_a_new(Core::CreationTag)
    end
  end

  describe "GET #edit" do
    it "assigns the requested core_creation_tag as @core_creation_tag" do
      creation_tag = Core::CreationTag.create! valid_attributes
      get :edit, {:id => creation_tag.to_param}, valid_session
      expect(assigns(:core_creation_tag)).to eq(creation_tag)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Core::CreationTag" do
        expect {
          post :create, {:core_creation_tag => valid_attributes}, valid_session
        }.to change(Core::CreationTag, :count).by(1)
      end

      it "assigns a newly created core_creation_tag as @core_creation_tag" do
        post :create, {:core_creation_tag => valid_attributes}, valid_session
        expect(assigns(:core_creation_tag)).to be_a(Core::CreationTag)
        expect(assigns(:core_creation_tag)).to be_persisted
      end

      it "redirects to the created core_creation_tag" do
        post :create, {:core_creation_tag => valid_attributes}, valid_session
        expect(response).to redirect_to(Core::CreationTag.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved core_creation_tag as @core_creation_tag" do
        post :create, {:core_creation_tag => invalid_attributes}, valid_session
        expect(assigns(:core_creation_tag)).to be_a_new(Core::CreationTag)
      end

      it "re-renders the 'new' template" do
        post :create, {:core_creation_tag => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested core_creation_tag" do
        creation_tag = Core::CreationTag.create! valid_attributes
        put :update, {:id => creation_tag.to_param, :core_creation_tag => new_attributes}, valid_session
        creation_tag.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested core_creation_tag as @core_creation_tag" do
        creation_tag = Core::CreationTag.create! valid_attributes
        put :update, {:id => creation_tag.to_param, :core_creation_tag => valid_attributes}, valid_session
        expect(assigns(:core_creation_tag)).to eq(creation_tag)
      end

      it "redirects to the core_creation_tag" do
        creation_tag = Core::CreationTag.create! valid_attributes
        put :update, {:id => creation_tag.to_param, :core_creation_tag => valid_attributes}, valid_session
        expect(response).to redirect_to(creation_tag)
      end
    end

    context "with invalid params" do
      it "assigns the core_creation_tag as @core_creation_tag" do
        creation_tag = Core::CreationTag.create! valid_attributes
        put :update, {:id => creation_tag.to_param, :core_creation_tag => invalid_attributes}, valid_session
        expect(assigns(:core_creation_tag)).to eq(creation_tag)
      end

      it "re-renders the 'edit' template" do
        creation_tag = Core::CreationTag.create! valid_attributes
        put :update, {:id => creation_tag.to_param, :core_creation_tag => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested core_creation_tag" do
      creation_tag = Core::CreationTag.create! valid_attributes
      expect {
        delete :destroy, {:id => creation_tag.to_param}, valid_session
      }.to change(Core::CreationTag, :count).by(-1)
    end

    it "redirects to the core_creation_tags list" do
      creation_tag = Core::CreationTag.create! valid_attributes
      delete :destroy, {:id => creation_tag.to_param}, valid_session
      expect(response).to redirect_to(core_creation_tags_url)
    end
  end

end
