require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Manage::CollectionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Manage::Collection. As you add validations to Manage::Collection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Manage::CollectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all manage_collections as @manage_collections" do
      collection = Manage::Collection.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:manage_collections)).to eq([collection])
    end
  end

  describe "GET #show" do
    it "assigns the requested manage_collection as @manage_collection" do
      collection = Manage::Collection.create! valid_attributes
      get :show, {:id => collection.to_param}, valid_session
      expect(assigns(:manage_collection)).to eq(collection)
    end
  end

  describe "GET #new" do
    it "assigns a new manage_collection as @manage_collection" do
      get :new, {}, valid_session
      expect(assigns(:manage_collection)).to be_a_new(Manage::Collection)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manage_collection as @manage_collection" do
      collection = Manage::Collection.create! valid_attributes
      get :edit, {:id => collection.to_param}, valid_session
      expect(assigns(:manage_collection)).to eq(collection)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Manage::Collection" do
        expect {
          post :create, {:manage_collection => valid_attributes}, valid_session
        }.to change(Manage::Collection, :count).by(1)
      end

      it "assigns a newly created manage_collection as @manage_collection" do
        post :create, {:manage_collection => valid_attributes}, valid_session
        expect(assigns(:manage_collection)).to be_a(Manage::Collection)
        expect(assigns(:manage_collection)).to be_persisted
      end

      it "redirects to the created manage_collection" do
        post :create, {:manage_collection => valid_attributes}, valid_session
        expect(response).to redirect_to(Manage::Collection.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manage_collection as @manage_collection" do
        post :create, {:manage_collection => invalid_attributes}, valid_session
        expect(assigns(:manage_collection)).to be_a_new(Manage::Collection)
      end

      it "re-renders the 'new' template" do
        post :create, {:manage_collection => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manage_collection" do
        collection = Manage::Collection.create! valid_attributes
        put :update, {:id => collection.to_param, :manage_collection => new_attributes}, valid_session
        collection.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manage_collection as @manage_collection" do
        collection = Manage::Collection.create! valid_attributes
        put :update, {:id => collection.to_param, :manage_collection => valid_attributes}, valid_session
        expect(assigns(:manage_collection)).to eq(collection)
      end

      it "redirects to the manage_collection" do
        collection = Manage::Collection.create! valid_attributes
        put :update, {:id => collection.to_param, :manage_collection => valid_attributes}, valid_session
        expect(response).to redirect_to(collection)
      end
    end

    context "with invalid params" do
      it "assigns the manage_collection as @manage_collection" do
        collection = Manage::Collection.create! valid_attributes
        put :update, {:id => collection.to_param, :manage_collection => invalid_attributes}, valid_session
        expect(assigns(:manage_collection)).to eq(collection)
      end

      it "re-renders the 'edit' template" do
        collection = Manage::Collection.create! valid_attributes
        put :update, {:id => collection.to_param, :manage_collection => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manage_collection" do
      collection = Manage::Collection.create! valid_attributes
      expect {
        delete :destroy, {:id => collection.to_param}, valid_session
      }.to change(Manage::Collection, :count).by(-1)
    end

    it "redirects to the manage_collections list" do
      collection = Manage::Collection.create! valid_attributes
      delete :destroy, {:id => collection.to_param}, valid_session
      expect(response).to redirect_to(manage_collections_url)
    end
  end

end
