require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Manage::GoodsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Manage::Good. As you add validations to Manage::Good, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Manage::GoodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all manage_goods as @manage_goods" do
      good = Manage::Good.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:manage_goods)).to eq([good])
    end
  end

  describe "GET #show" do
    it "assigns the requested manage_good as @manage_good" do
      good = Manage::Good.create! valid_attributes
      get :show, {:id => good.to_param}, valid_session
      expect(assigns(:manage_good)).to eq(good)
    end
  end

  describe "GET #new" do
    it "assigns a new manage_good as @manage_good" do
      get :new, {}, valid_session
      expect(assigns(:manage_good)).to be_a_new(Manage::Good)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manage_good as @manage_good" do
      good = Manage::Good.create! valid_attributes
      get :edit, {:id => good.to_param}, valid_session
      expect(assigns(:manage_good)).to eq(good)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Manage::Good" do
        expect {
          post :create, {:manage_good => valid_attributes}, valid_session
        }.to change(Manage::Good, :count).by(1)
      end

      it "assigns a newly created manage_good as @manage_good" do
        post :create, {:manage_good => valid_attributes}, valid_session
        expect(assigns(:manage_good)).to be_a(Manage::Good)
        expect(assigns(:manage_good)).to be_persisted
      end

      it "redirects to the created manage_good" do
        post :create, {:manage_good => valid_attributes}, valid_session
        expect(response).to redirect_to(Manage::Good.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manage_good as @manage_good" do
        post :create, {:manage_good => invalid_attributes}, valid_session
        expect(assigns(:manage_good)).to be_a_new(Manage::Good)
      end

      it "re-renders the 'new' template" do
        post :create, {:manage_good => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manage_good" do
        good = Manage::Good.create! valid_attributes
        put :update, {:id => good.to_param, :manage_good => new_attributes}, valid_session
        good.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manage_good as @manage_good" do
        good = Manage::Good.create! valid_attributes
        put :update, {:id => good.to_param, :manage_good => valid_attributes}, valid_session
        expect(assigns(:manage_good)).to eq(good)
      end

      it "redirects to the manage_good" do
        good = Manage::Good.create! valid_attributes
        put :update, {:id => good.to_param, :manage_good => valid_attributes}, valid_session
        expect(response).to redirect_to(good)
      end
    end

    context "with invalid params" do
      it "assigns the manage_good as @manage_good" do
        good = Manage::Good.create! valid_attributes
        put :update, {:id => good.to_param, :manage_good => invalid_attributes}, valid_session
        expect(assigns(:manage_good)).to eq(good)
      end

      it "re-renders the 'edit' template" do
        good = Manage::Good.create! valid_attributes
        put :update, {:id => good.to_param, :manage_good => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manage_good" do
      good = Manage::Good.create! valid_attributes
      expect {
        delete :destroy, {:id => good.to_param}, valid_session
      }.to change(Manage::Good, :count).by(-1)
    end

    it "redirects to the manage_goods list" do
      good = Manage::Good.create! valid_attributes
      delete :destroy, {:id => good.to_param}, valid_session
      expect(response).to redirect_to(manage_goods_url)
    end
  end

end
