require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Manage::ReportsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Manage::Report. As you add validations to Manage::Report, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Manage::ReportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all manage_reports as @manage_reports" do
      report = Manage::Report.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:manage_reports)).to eq([report])
    end
  end

  describe "GET #show" do
    it "assigns the requested manage_report as @manage_report" do
      report = Manage::Report.create! valid_attributes
      get :show, {:id => report.to_param}, valid_session
      expect(assigns(:manage_report)).to eq(report)
    end
  end

  describe "GET #new" do
    it "assigns a new manage_report as @manage_report" do
      get :new, {}, valid_session
      expect(assigns(:manage_report)).to be_a_new(Manage::Report)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manage_report as @manage_report" do
      report = Manage::Report.create! valid_attributes
      get :edit, {:id => report.to_param}, valid_session
      expect(assigns(:manage_report)).to eq(report)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Manage::Report" do
        expect {
          post :create, {:manage_report => valid_attributes}, valid_session
        }.to change(Manage::Report, :count).by(1)
      end

      it "assigns a newly created manage_report as @manage_report" do
        post :create, {:manage_report => valid_attributes}, valid_session
        expect(assigns(:manage_report)).to be_a(Manage::Report)
        expect(assigns(:manage_report)).to be_persisted
      end

      it "redirects to the created manage_report" do
        post :create, {:manage_report => valid_attributes}, valid_session
        expect(response).to redirect_to(Manage::Report.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manage_report as @manage_report" do
        post :create, {:manage_report => invalid_attributes}, valid_session
        expect(assigns(:manage_report)).to be_a_new(Manage::Report)
      end

      it "re-renders the 'new' template" do
        post :create, {:manage_report => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manage_report" do
        report = Manage::Report.create! valid_attributes
        put :update, {:id => report.to_param, :manage_report => new_attributes}, valid_session
        report.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manage_report as @manage_report" do
        report = Manage::Report.create! valid_attributes
        put :update, {:id => report.to_param, :manage_report => valid_attributes}, valid_session
        expect(assigns(:manage_report)).to eq(report)
      end

      it "redirects to the manage_report" do
        report = Manage::Report.create! valid_attributes
        put :update, {:id => report.to_param, :manage_report => valid_attributes}, valid_session
        expect(response).to redirect_to(report)
      end
    end

    context "with invalid params" do
      it "assigns the manage_report as @manage_report" do
        report = Manage::Report.create! valid_attributes
        put :update, {:id => report.to_param, :manage_report => invalid_attributes}, valid_session
        expect(assigns(:manage_report)).to eq(report)
      end

      it "re-renders the 'edit' template" do
        report = Manage::Report.create! valid_attributes
        put :update, {:id => report.to_param, :manage_report => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manage_report" do
      report = Manage::Report.create! valid_attributes
      expect {
        delete :destroy, {:id => report.to_param}, valid_session
      }.to change(Manage::Report, :count).by(-1)
    end

    it "redirects to the manage_reports list" do
      report = Manage::Report.create! valid_attributes
      delete :destroy, {:id => report.to_param}, valid_session
      expect(response).to redirect_to(manage_reports_url)
    end
  end

end
