#=======================================
# Format
#---------------------------------------
#
# <controller_name>:
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   ...
# <controller_name>:
#   ...
#
#=======================================
# Example
#---------------------------------------
#
# authors:       # AuthorsController
#   create:      # :create method
#     - manager  # "manager" role
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
# books:
#   create:
#     - manager
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
#

default: &controller_default
  index: &action_default
    - unauthenticated
  create:
    *action_default
  new:
    *action_default
  edit:
    *action_default
  show:
    *action_default
  update:
    *action_default
  destroy:
    *action_default

#
# SAMPLE
#
# authors:
#   <<: *controller_default

creations:
  <<: *controller_default
  index_created_by_user:
    *action_default
  index_latest:
    *action_default
  
site_users:
  <<: *controller_default
  show_my_info:
    *action_default
